# **Manufacturing project**

## 1. Import Libraries

In [125]:
import pandas as pd
import numpy as np

## 2. Load Data

In [126]:
file_path = "Manufacturing_Line_Productivity.xlsx"
xls = pd.ExcelFile(file_path)
xls.sheet_names

['Line productivity', 'Products', 'Downtime factors', 'Line downtime']

### Load each sheet into a separate DataFrame

In [127]:
# Load each sheet into a separate DataFrame
productivity = pd.read_excel(file_path, sheet_name='Line productivity')
products = pd.read_excel(file_path, sheet_name='Products')
downtime_factors = pd.read_excel(file_path, sheet_name='Downtime factors')
line_downtime = pd.read_excel(file_path, sheet_name='Line downtime')

## 3. Initial inspection

### 3.1 Review structure and the first rows of each dataset

In [128]:
productivity.info()
productivity.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        38 non-null     datetime64[ns]
 1   Product     38 non-null     object
 2   Batch       38 non-null     int64
 3   Operator    38 non-null     object
 4   Start Time  38 non-null     object
 5   End Time    38 non-null     object
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 1.9+ KB

        Date Product   Batch Operator Start Time  End Time
0 2024-08-29  OR-600  422111      Mac   11:50:00  14:05:00
1 2024-08-29  LE-600  422112      Mac   14:05:00  15:45:00
2 2024-08-29  LE-600  422113      Mac   15:45:00  17:35:00
3 2024-08-29  LE-600  422114      Mac   17:35:00  19:15:00
4 2024-08-29  LE-600  422115  Charlie   19:15:00  20:39:00

In [129]:
products.info()
products.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Product         6 non-null      object
 1   Flavor          6 non-null      object
 2   Size            6 non-null      object
 3   Min batch time  6 non-null      int64
dtypes: int64(1), object(3)
memory usage: 324.0+ bytes

  Product      Flavor    Size  Min batch time
0  OR-600      Orange  600 ml              60
1  LE-600  Lemon lime  600 ml              60
2  CO-600        Cola  600 ml              60
3  DC-600   Diet Cola  600 ml              60
4  RB-600   Root Beer  600 ml              60

In [130]:
downtime_factors.info()
downtime_factors.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Factor          12 non-null     int64
 1   Description     12 non-null     object
 2   Operator Error  12 non-null     object
dtypes: int64(1), object(2)
memory usage: 420.0+ bytes

   Factor         Description Operator Error
0       1      Emergency stop             No
1       2        Batch change            Yes
2       3      Labeling error             No
3       4  Inventory shortage             No
4       5       Product spill            Yes

In [131]:
line_downtime.info()
line_downtime.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       39 non-null     object
 1   Downtime factor  1 non-null      float64
 2   Unnamed: 2       6 non-null      float64
 3   Unnamed: 3       3 non-null      float64
 4   Unnamed: 4       10 non-null     float64
 5   Unnamed: 5       4 non-null      float64
 6   Unnamed: 6       13 non-null     float64
 7   Unnamed: 7       12 non-null     float64
 8   Unnamed: 8       7 non-null      float64
 9   Unnamed: 9       2 non-null      float64
 10  Unnamed: 10      4 non-null      float64
 11  Unnamed: 11      4 non-null      float64
 12  Unnamed: 12      7 non-null      float64
dtypes: float64(12), object(1)
memory usage: 4.1+ KB

,Unnamed: 0,Downtime factor,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Batch,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0
1,422111,NaN,60.0,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,NaN
2,422112,NaN,20.0,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN
3,422113,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,422114,NaN,NaN,NaN,25.0,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN

### 3.2 Fix Incorrect Header in line_downtime Table

#### During the initial inspection of the Line downtime worksheet, it was observed that the column names were not imported correctly. Most columns were labeled as Unnamed, indicating that the actual headers were stored in the second row of the Excel sheet.

In [132]:
line_downtime = pd.read_excel(
    file_path,
    sheet_name='Line downtime',
    header=1
)

line_downtime.head()

    Batch   1     2   3     4   5     6     7     8   9    10  11  12
0  422111 NaN  60.0 NaN   NaN NaN   NaN  15.0   NaN NaN   NaN NaN NaN
1  422112 NaN  20.0 NaN   NaN NaN   NaN   NaN  20.0 NaN   NaN NaN NaN
2  422113 NaN  50.0 NaN   NaN NaN   NaN   NaN   NaN NaN   NaN NaN NaN
3  422114 NaN   NaN NaN  25.0 NaN  15.0   NaN   NaN NaN   NaN NaN NaN
4  422115 NaN   NaN NaN   NaN NaN   NaN   NaN   NaN NaN  24.0 NaN NaN

## 4. Dataset Overview

### 4.1 Check dataset dimensions

In [133]:
print("Productivity:", productivity.shape)
print("Products:", products.shape)
print("Downtime factors:", downtime_factors.shape)
print("Line downtime:", line_downtime.shape)

Productivity: (38, 6)
Products: (6, 4)
Downtime factors: (12, 3)
Line downtime: (38, 13)

### 4.2  Missing Values Check

In [134]:
print(productivity.isna().sum())
print()
print(products.isna().sum())
print()
print(downtime_factors.isna().sum())
print()
print(line_downtime.isna().sum())

Date          0
Product       0
Batch         0
Operator      0
Start Time    0
End Time      0
dtype: int64

Product           0
Flavor            0
Size              0
Min batch time    0
dtype: int64

Factor            0
Description       0
Operator Error    0
dtype: int64

Batch     0
1        38
2        33
3        36
4        29
5        35
6        26
7        27
8        32
9        37
10       35
11       35
12       32
dtype: int64

### 4.3 Uniqueness & duplicates Check

#### Verify if potential keys are unique and that no duplicate records exist before performing data transformations and table joins.

In [135]:
print("UNIQUE VALUES")
print(f"Unique batches in Productivity: {productivity['Batch'].nunique()}")
print(f"Unique products in Products: {products['Product'].nunique()}")
print(f"Unique factors in Downtime Factors: {downtime_factors['Factor'].nunique()}")

print("\nDUPLICATES")
print(f"Productivity duplicates: {productivity.duplicated().sum()}")
print(f"Products duplicates: {products.duplicated().sum()}")
print(f"Downtime Factors duplicates: {downtime_factors.duplicated().sum()}")
print(f"Line Downtime duplicates: {line_downtime.duplicated().sum()}")

UNIQUE VALUES
Unique batches in Productivity: 38
Unique products in Products: 6
Unique factors in Downtime Factors: 12

DUPLICATES
Productivity duplicates: 0
Products duplicates: 0
Downtime Factors duplicates: 0
Line Downtime duplicates: 0

### 4.4 Data Types Review

In [136]:
print(productivity.dtypes)
print()
print(products.dtypes)
print()
print(downtime_factors.dtypes)
print()
print(line_downtime.dtypes)

Date          datetime64[ns]
Product               object
Batch                  int64
Operator              object
Start Time            object
End Time              object
dtype: object

Product           object
Flavor            object
Size              object
Min batch time     int64
dtype: object

Factor             int64
Description       object
Operator Error    object
dtype: object

Batch      int64
1        float64
2        float64
3        float64
4        float64
5        float64
6        float64
7        float64
8        float64
9        float64
10       float64
11       float64
12       float64
dtype: object

## 5. Calculations

### Create full production timestamps and calculate batch duration

In [137]:
# Create full production timestamps

productivity['Start_DateTime'] = pd.to_datetime(
    productivity['Date'].dt.strftime('%Y-%m-%d')
    + ' '
    + productivity['Start Time'].astype(str)
)

productivity['End_DateTime'] = pd.to_datetime(
    productivity['Date'].dt.strftime('%Y-%m-%d')
    + ' '
    + productivity['End Time'].astype(str)
)

# Handle batches crossing midnight
overnight_batches = productivity['End_DateTime'] < productivity['Start_DateTime']

productivity.loc[overnight_batches, 'End_DateTime'] = (
    productivity.loc[overnight_batches, 'End_DateTime']
    + pd.Timedelta(days=1)
)

# Calculate actual production time in minutes
productivity['Actual_Batch_Time_Min'] = (
    productivity['End_DateTime']
    - productivity['Start_DateTime']
).dt.total_seconds() / 60

print(productivity['Actual_Batch_Time_Min'].head())

0    135.0
1    100.0
2    110.0
3    100.0
4     84.0
Name: Actual_Batch_Time_Min, dtype: float64

## 6. Transform line_downtime Table

### Transform downtime data from wide to long format

In [138]:
downtime_long = line_downtime.melt(
    id_vars='Batch',
    var_name='Factor',
    value_name='Downtime_Min'
)

downtime_long = downtime_long.dropna(
    subset=['Downtime_Min']
)

downtime_long.head(10)

      Batch Factor  Downtime_Min
38   422111      2          60.0
39   422112      2          20.0
40   422113      2          50.0
44   422117      2          10.0
57   422130      2          20.0
103  422138      3          20.0
110  422145      3          22.0
117  422114      4          25.0
122  422119      4          25.0
123  422120      4          20.0

In [139]:
downtime_long.head()
downtime_long.info()

<class 'pandas.core.frame.DataFrame'>
Index: 61 entries, 38 to 453
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Batch         61 non-null     int64
 1   Factor        61 non-null     object
 2   Downtime_Min  61 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.9+ KB

## 7. Export Data

In [140]:
productivity.to_csv(
    'Productivity.csv',
    index=False
)

downtime_long.to_csv(
    'Downtime.csv',
    index=False
)

products.to_csv(
    'Product.csv',
    index=False
)

downtime_factors.to_csv(
    'Downtime_factor.csv',
    index=False
)

## 8. Data Preparation Summary

#### The raw manufacturing dataset was cleaned and transformed to support further SQL analysis and Power BI reporting.

#### Key preparation steps:
#### - Corrected improperly imported headers.
#### - Validated uniqueness and duplicates.
#### - Calculated actual batch duration.
#### - Handled batches crossing midnight.
#### - Reshaped downtime data from wide to long format.
#### - Exported cleaned datasets for relational analysis.